### PR TITLE
Minimal changes to work with Blender 2.8x, backward compatible.

### PR DESCRIPTION
**Pull request by Houmgaor**
Everything is in the title. No bugs were spotted neither on FMOD or FSKLimport.

### CODE REVIEW

**Comment by AsteriskAmpersand** [comment]
I'm not sold on the use of a colossal amount of version dependent conditionals being the actual solution. Having a separate clean fork for 2.8+ without backwards compatibility would be the direction to go in terms of making the already messy code less of a maintenance nightmare. Or some properly elegant abstraction of dealing with blender versioning situation.

**Comment by Houmgaor** [comment]
Most of the changes are blank spaces: automatic PEP 8 style enforcement. 

1 method was added: `` FModImporter.createTextureLayerFromObj``. 

The rest of the changes consist of:

```python
if hasattr(obj, 'method'):
    obj.method()
else:
    obj.old_method()
```

Which I wrote something like 10 times.

I don't think it a maintenance nightmare. I wrote the code this way because I tend to keep backward compatibility for great tools, such as Frontier Importer, when I can. Would you like a new PR backward incompatible with PEP 8 violations?

**Comment by AsteriskAmpersand** [comment]
Its not the PEP changes, its that pattern, that solution shouldn't be a spraying of conditionals all over the place, it really should be a wrapper or some additional layer of version compatibility that abstracts the api calls. That's a quick hack not an actual solution.

**Comment by Houmgaor** [comment]
Blender does not provide abstractions to handle this kind of versioning issue. What about creating a new branch "2.79" with the current state of the repo, and moving on with the updated methods on *master* for the new Blender releases?

**Pull request closed without merging**
